### ISSUE TITLE
Handle API limits

### ISSUE THREAD

**Issue by reiz** [versioneye/veye-checker#1]
By default the VersionEye API is limited to 50 calls per hour. If that limit is reached the Rust tool should handle that and output a nice message to the user. Something like: 

```
You reached the API limit. Please go to https://www.versioneye.com and subscribe to a higher plan to get a higher API rate limit. 
```

**Comment by timgluz** [comment]
Full api response after reaching API limit:

```json

{
  "error": "API rate limit of 50 calls per hour exceeded. Upgrade to a higher plan if you need a higher rate limit. Used API Key: b5fff0a8fbad91d5a713"
}
```

**Comment by timgluz** [comment]
TODO: print proper error message with url and stop execution;

**Comment by timgluz** [comment]
It now prints out error message from API;
