### ISSUE TITLE
command specs

### ISSUE THREAD

**Issue by reiz** [versioneye/veye-checker#10]
The command specs should look like this: 

## shas
The command `shas` should generate the SHA values for the files in a target directory. For example: 

```
veye_checker shas . 
```

That would recursively walk through the current directory and generate SHA values for certain files. Here another example: 

```
veye_checker shas ../extlib -o shas.csv
```

The above command would walk through the "../extlib" directory, generate SHA values for them and write the output to the `shas.csv` file. 

## resolve
The command `resolve` should generate the SHA values for the files in a target directory AND resolve the SHA values to their coordinates in package managers, by using the VersionEye API. Here an example: 

```
veye_checker resolve . 
```

If no output file is defined the output goes to the console. Here is an example where an output file is defined.

```
veye_checker resolve myDirectory -o results.csv
```

**Comment by timgluz** [comment]
solved in `0.1.0-RC2`
