### ISSUE TITLE
Handle situations when the `/product/shas` return more than 1 items.

### ISSUE THREAD

**Issue by timgluz** [versioneye/veye-checker#13]
The `/product/shas` returns array, which may have N items. But mostly it's just empty or just 1item; But with MD5 and SHA1 there may have collisions and it may return multiple items;

**Comment by reiz** [comment]
@timgluz Can this lead to a crash? Is this a bug?

**Comment by timgluz** [comment]
No, current solution will use only 1st match and will ignore others. It's not critical as probability of SHA collision is pretty low. But it'll be fixed somepoint in near future.

**Comment by timgluz** [comment]
Resolved = it now prints each of result into own line;
