### ISSUE TITLE
Product URL has wrong base URL

### ISSUE THREAD

**Issue by svogt** [versioneye/veye-checker#17]
When setting the `VERSIONEYE_API_HOST` and `VERSIONEYE_API_SCHEME` the CSV still has product URLs to the public `https://www.versioneye.com/...` - should use the local Versioneye instance

**Comment by timgluz** [comment]
Thanks, it's going to be fixed in next version.

**Comment by timgluz** [comment]
Done - it uses now data from API configs to build product url;
