### ISSUE TITLE
VERSIONEYE_API_KEY

### ISSUE THREAD

**Issue by reiz** [versioneye/veye-checker#2]
The Rust tool should first look for the API key in the environment variable `VERSIONEYE_API_KEY`. People how are using the VersionEye Maven Plugin are usually exporting it already like this: 

```
export VERSIONEYE_API_KEY=my_secret_api_key
```

**Comment by timgluz** [comment]
Docs with usage will follow soon.

**Comment by timgluz** [comment]
Done, it's possible to tweak various API related configurations via ENV vars or via config file.

**Comment by reiz** [comment]
Cool 👍
