### ISSUE TITLE
release 0.2.0

### ISSUE THREAD

**Issue by timgluz** [versioneye/veye-checker#22]
* clean compiler warnings
* update dependencies
* update readme with scan configs for `min-file-size` and `max-file-size`
* update acceptance tests

* add protected branch just for releases
* add checksums for releases;

**Comment by reiz** [comment]
@timgluz Cool. I will test it this week. Have a client project where I need to identify dependencies based on binaries!

**Comment by timgluz** [comment]
I will release new version tomorrow - upgrading `hyper` takes more effort than i thought and that tasks needs a little bit yak-shaving to get proxy work;

**Comment by timgluz** [comment]
Done!
